from PIL import Image, ExifTags

AI_TAGS = [
    "midjourney", "stable diffusion", "stablediffusion", "stable-diffusion",
    "dall-e", "dall e", "dalle", "firefly", "adobe firefly", "comfyui",
    "automatic1111", "novelai", "leonardo", "ideogram", "nano banana",
    "gemini", "flux", "imagen", "krea", "topaz", "diffusion", "ai-generated",
    "generated by", "synthetic",
]


def _open(x):
    if isinstance(x, Image.Image):
        return x
    if isinstance(x, str):
        return Image.open(x)
    raise TypeError("expected a path or PIL.Image")


def _has_ai(s):
    sl = s.lower()
    return [t for t in AI_TAGS if t in sl]


def analyze_metadata(image):
    """Return summary_text (string)."""
    img = _open(image)
    lines, flags = [], []

    exif = img.getexif() if hasattr(img, "getexif") else None
    if exif:
        for tag, val in exif.items():
            name = ExifTags.TAGS.get(tag, str(tag))
            sval = str(val)
            lines.append(f"{name}: {sval[:300]}")
            flags += [f"EXIF {name}='{sval[:80]}'" for _ in _has_ai(sval)]

    for k, v in (img.info or {}).items():
        sv = str(v)
        if k.lower() in ("exif", "icc_profile") and len(sv) > 300:
            sv = sv[:300] + "..."
        lines.append(f"{k}: {sv[:300]}")
        flags += [f"{k}='{sv[:80]}'" for _ in _has_ai(sv)]

    if flags:
        head = "AI tool tags detected (strong evidence of AI):\n- " + "\n- ".join(dict.fromkeys(flags))
    else:
        head = "No known AI tool tags detected."

    if not lines:
        body = ("\nNo EXIF / metadata present.\nMost social platforms strip metadata, and AI "
                "exports often ship with none. Absence is weak evidence; a present AI tool tag "
                "is strong evidence.")
    else:
        body = "\n\n--- Raw metadata ---\n" + "\n".join(lines)

    return head + body